# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-14 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0008_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsxHost',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('version', models.CharField(choices=[(b'ESXI_55', b'VMware vSphere Hypervisor (ESXi) 5.5'), (b'ESXI_60', b'VMware vSphere Hypervisor (ESXi) 6.0'), (b'ESXI_65', b'VMware vSphere Hypervisor (ESXi) 6.5')], help_text=b"Version, one of ['ESXI_55', 'ESXI_60', 'ESXI_65']", max_length=16)),
                ('ipv4', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('location', models.ForeignKey(help_text=b'The location of this Esx host', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
