# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_vsphere_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esxhost',
            name='location',
            field=models.ForeignKey(help_text='The location of this Esx host', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location'),
        ),
        migrations.AlterField(
            model_name='esxhost',
            name='version',
            field=models.CharField(choices=[('ESXI_55', 'VMware vSphere Hypervisor (ESXi) 5.5'), ('ESXI_60', 'VMware vSphere Hypervisor (ESXi) 6.0'), ('ESXI_65', 'VMware vSphere Hypervisor (ESXi) 6.5')], help_text="Version, one of ['ESXI_55', 'ESXI_60', 'ESXI_65']", max_length=16),
        ),
    ]
