# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_vsphere_items', '0002_update_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='esxhost',
            name='vcenter',
            field=models.CharField(default='eng-vcenter5.colo.rubrik.com',
                                   max_length=128),
            preserve_default=False,
        ),
    ]
