# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def change_existing_networks(apps, schema_editor):
    EsxHost = apps.get_model('bodega_vsphere_items', 'EsxHost')
    Network = apps.get_model('bodega_core', 'Network')

    for esx_host in EsxHost.objects.all():
        network = Network.objects.get(location=esx_host.location,
                                      name='native')
        esx_host.network = network
        esx_host.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0013_network'),
        ('bodega_vsphere_items', '0003_esx_vcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='esxhost',
            name='network',
            field=models.ForeignKey(default=1,
                                    help_text='The network of this EsxHost.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='bodega_core.Network'),
            preserve_default=False,
        ),
        migrations.RunPython(change_existing_networks,
                             reverse_code=migrations.RunPython.noop
        ),
    ]
