# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0012_order_tab_based_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CockroachDBDepsMachine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('disk_size', models.IntegerField(choices=[(32, 32), (64, 64), (128, 128), (256, 256)], default=32, help_text='Disk size in GB, one of [32, 64, 128, 256]')),
                ('version', models.CharField(choices=[('14.04', '14.04')], default='14.04', help_text="Version, one of ['14.04']", max_length=16)),
                ('model', models.CharField(default='aws-m4.large', max_length=64)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text='The location of this CockroachDBDepsMachine.', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
