# Generated by Django 1.10.4 on 2018-05-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def change_existing_networks(apps, schema_editor):
    CockroachDBDepsMachine = apps.get_model('bodega_crdb_dev_items',
                                            'CockroachDBDepsMachine')
    Network = apps.get_model('bodega_core', 'Network')

    for cockroachdb_deps_machine in CockroachDBDepsMachine.objects.all():
        location = cockroachdb_deps_machine.location
        if location.name == 'AWS-US-WEST-1':
            network = Network.objects.get(location=location,
                                          name='vpc-c77e84a3')
        elif location.name == 'AWS-AP-SOUTH-1':
            network = Network.objects.get(location=location,
                                          name='vpc-966f67ff')
        else:
            network = Network.objects.get(location=location,
                                          name='native')
        cockroachdb_deps_machine.network = network
        cockroachdb_deps_machine.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0013_network'),
        ('bodega_crdb_dev_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockroachdbdepsmachine',
            name='network',
            field=models.ForeignKey(default=1,
                                    help_text='The network of this CockroachDBDepsMachine.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='bodega_core.Network'),
            preserve_default=False,
        ),
        migrations.RunPython(change_existing_networks,
                             reverse_code=migrations.RunPython.noop
        ),
    ]
