# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_crdb_dev_items', '0002_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockroachdbdepsmachine',
            name='image_version',
            field=models.CharField(blank=True, help_text='Version of the image to build cockroachdb_deps_machine with.', max_length=64),
        ),
    ]
