# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('held_by_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('time_held_by_object_updated', models.DateTimeField(auto_now_add=True, help_text=b'The last time the holder of this object was updated.')),
                ('held_by_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemFulfillment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(help_text=b'The customer nickname for the required item.', max_length=128)),
                ('item', models.ForeignKey(help_text=b'The item used to (partially) fulfill the order.', on_delete=django.db.models.deletion.CASCADE, related_name='item_fulfillments', to='bodega_core.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(b'OPEN', b'Open'), (b'FULFILLED', b'Fulfilled'), (b'CLOSED', b'Closed')], help_text=b"Order status, one of ['OPEN', 'FULFILLED', 'CLOSED']", max_length=16)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creator_object_id', models.PositiveIntegerField(blank=True)),
                ('comment', models.TextField(blank=True, default=b'', help_text=b'')),
                ('items_delta', models.TextField(blank=True, default=b'', help_text=b'Items to add to the order.')),
                ('new_status', models.CharField(blank=True, choices=[(b'OPEN', b'Open'), (b'FULFILLED', b'Fulfilled'), (b'CLOSED', b'Closed')], default=b'', help_text=b"Order status, one of ['OPEN', 'FULFILLED', 'CLOSED']", max_length=16)),
                ('time_limit_delta', models.DurationField(default=datetime.timedelta(0), help_text=b'Timedelta (Format: [DD] [HH:[MM:]]ss[.uuuuuu]) to extend the current lease')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_limit_notice', models.BooleanField(default=False)),
                ('creator_content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('order', models.ForeignKey(help_text=b'ID of Order object to update', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='bodega_core.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemfulfillment',
            name='order_update',
            field=models.ForeignKey(help_text=b'The order update this fulfullment is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='item_fulfillments', to='bodega_core.OrderUpdate'),
        ),
    ]
