# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[(b'ACTIVE', b'Active'), (b'DESTROYED', b'Destroyed'), (b'MAINTENANCE', b'Maintenance')], default=b'ACTIVE', help_text=b"Order status, one of ['ACTIVE', 'DESTROYED', 'MAINTENANCE']", max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='maintenance',
            field=models.BooleanField(default=False, help_text=b'New order is a maintenance order.'),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
