# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0005_orderupdate_expiration_time_limit_delta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
