# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def set_order_tab(apps, schema_editor):
    Order = apps.get_model('bodega_core', 'Order')
    Tab = apps.get_model('bodega_core', 'Tab')
    for order in Order.objects.all():
        order_owner = order.owner
        order_tab = Tab.objects.get(owner=order_owner)
        order.tab = order_tab
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0008_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tab',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='charged_orders',
                                    to='bodega_core.Tab'),
            preserve_default=False,
        ),
        migrations.RunPython(set_order_tab,
                             reverse_code=migrations.RunPython.noop),
    ]
