# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0010_update_strings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockroom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(help_text='Location of the stockroom', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
