# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0011_stockroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tab_based_priority',
            field=models.IntegerField(default=-1, help_text='Last known priority of the order.'),
        ),
    ]
