# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_default_networks(apps, schema_editor):
    Location = apps.get_model('bodega_core', 'Location')
    Network = apps.get_model('bodega_core', 'Network')

    locations = Location.objects.all()
    for location in locations:
        if location.name == 'AWS-US-WEST-1':
            Network.objects.create(location=location,
                                   name='vpc-c77e84a3')
            Network.objects.create(location=location,
                                   name='default')
        elif location.name == 'AWS-AP-SOUTH-1':
            Network.objects.create(location=location,
                                   name='default')
            Network.objects.create(location=location,
                                   name='undefined')
        else:
            # Assuming that we are in HQ, COLO, or Bangalore
            Network.objects.create(location=location,
                                   name='native')


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0012_order_tab_based_priority'),
        ('bodega_aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfulfillment',
            name='order_update',
            field=models.ForeignKey(help_text='The order update this fulfillment is a part of.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='item_fulfillments',
                                    to='bodega_core.OrderUpdate'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='bodega_core.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together=set([('location', 'name')]),
        ),
        migrations.RunPython(create_default_networks,
                             reverse_code=migrations.RunPython.noop,
        ),
    ]
