# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The UUID tag used to identify builds from the Jenkins API.')),
                ('cached_job_url', models.URLField(help_text='The cached URL of a Jenkins job, used for display only.', null=True)),
                ('cached_buildnum', models.PositiveIntegerField(help_text='The cached buildnum of a Jenkins build.', null=True)),
                ('time_uuid_updated', models.DateTimeField(auto_now_add=True, help_text='The last time the UUID of this task was updated.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseQualBaton',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
        migrations.CreateModel(
            name='RktestYml',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('filename', models.CharField(help_text='Filename of the rktest.yml item', max_length=80)),
                ('description', models.TextField(blank=True, default='', help_text='Description of this RktestYml item.')),
                ('location', models.CharField(choices=[('_COLO', '_COLO'), ('_HQ', '_HQ')], help_text="Location, one of [u'_COLO', u'_HQ']", max_length=5)),
                ('platform', models.CharField(choices=[('DYNAPOD', 'DYNAPOD'), ('DYNAPOD_ROBO', 'DYNAPOD_ROBO'), ('PROD_BRIK', 'PROD_BRIK'), ('STATIC', 'STATIC'), ('STATIC_ROBO', 'STATIC_ROBO')], help_text="Platform, one of [u'DYNAPOD', u'DYNAPOD_ROBO', u'PROD_BRIK', u'STATIC', u'STATIC_ROBO']", max_length=12)),
                ('benchmarking', models.BooleanField(default=False, help_text='Usable for benchmarking')),
                ('encrypted', models.BooleanField(default=False, help_text='Is encrypted')),
                ('linux_agent', models.BooleanField(default=False, help_text='Has Centos 6 and Ubuntu 14')),
                ('linux_agent_all_versions', models.BooleanField(default=False, help_text='Has Centos 5,6,7 and Ubuntu 12,14,16')),
                ('manufacturable', models.BooleanField(default=False, help_text='Is manufacturable')),
                ('mssql', models.BooleanField(default=False, help_text='Has MSSQL')),
                ('robofm', models.BooleanField(default=False, help_text='Has fileset and mssql components')),
                ('robossd', models.BooleanField(default=False, help_text='Has an ssd for the OS')),
                ('vcenter_5_1', models.BooleanField(default=False, help_text='Has VCenter 5.1')),
                ('vcenter_5_5', models.BooleanField(default=False, help_text='Has VCenter 5.5')),
                ('vcenter_6_0', models.BooleanField(default=False, help_text='Has VCenter 6.0')),
                ('windows_app_test_only', models.BooleanField(default=False, help_text='Has resources for testing windows applications')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
