# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='tpm',
            field=models.BooleanField(default=False, help_text='Has TPM'),
        ),
    ]
