# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def change_existing_locations(apps, schema_editor):
    RktestYml = apps.get_model('bodega_legacy_items', 'RktestYml')
    Location = apps.get_model('bodega_core', 'Location')

    for rktest_yml in RktestYml.objects.all():
        location = Location.objects.get(name=rktest_yml.location_legacy.lstrip('_'))
        rktest_yml.location = location
        rktest_yml.save()


def revert_existing_locations(apps, schema_editor):
    RktestYml = apps.get_model('bodega_legacy_items', 'RktestYml')

    for rktest_yml in RktestYml.objects.all():
        rktest_yml.location_legacy = rktest_yml.location.name
        rktest_yml.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0007_add_new_locations'),
        ('bodega_legacy_items', '0003_rktestyml_vcenter_6_5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rktestyml',
            old_name='location',
            new_name='location_legacy',
        ),
        migrations.AddField(
            model_name='rktestyml',
            name='location',
            field=models.ForeignKey(
                help_text='The location of this RktestYml.',
                on_delete=django.db.models.deletion.CASCADE,
                to='bodega_core.Location',
                default=1),
            preserve_default=False,
        ),
        migrations.RunPython(change_existing_locations,
                             reverse_code=revert_existing_locations,
        ),
        migrations.RemoveField(
            model_name='rktestyml',
            name='location_legacy',
        )
    ]
