# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0004_location_field_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='hyperv_2016',
            field=models.BooleanField(default=False, help_text='Has HyperV 2016 host and VMs'),
        ),
    ]
