# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0005_rktestyml_hyperv_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='esx_6_0',
            field=models.BooleanField(default=False, help_text='Has ESX 6.0 host for general purpose usage'),
        ),
    ]
