# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0006_rktestyml_esx_6_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='acropolis',
            field=models.BooleanField(default=False, help_text='Has Acropolis host and VMs'),
        ),
    ]
