# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0009_azure_pod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rktestyml',
            name='platform',
            field=models.CharField(choices=[('AWSPOD', 'AWSPOD'), ('AZUREPOD', 'AZUREPOD'), ('CISCO', 'CISCO'), ('DYNAPOD', 'DYNAPOD'), ('DYNAPOD_ROBO', 'DYNAPOD_ROBO'), ('HPE', 'HPE'), ('LENOVO', 'LENOVO'), ('PROD_BRIK', 'PROD_BRIK'), ('STATIC', 'STATIC'), ('STATIC_ROBO', 'STATIC_ROBO')], help_text="Platform, one of [u'AWSPOD', u'AZUREPOD', u'CISCO', u'DYNAPOD', u'DYNAPOD_ROBO', u'HPE', u'LENOVO', u'PROD_BRIK', u'STATIC', u'STATIC_ROBO']", max_length=12),
        ),
    ]
