# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-15 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0011_dell'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='model_r6xx',
            field=models.BooleanField(default=False,help_text='Is R6xx series'),
        ),
    ]
