# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0012_rktestyml_model_r6xx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rktestyml',
            name='platform',
            field=models.CharField(choices=[('AWSPOD', 'AWSPOD'), ('AZUREPOD', 'AZUREPOD'), ('CISCO', 'CISCO'), ('DELL', 'DELL'), ('DYNAPOD', 'DYNAPOD'), ('DYNAPOD_ROBO', 'DYNAPOD_ROBO'), ('HPE', 'HPE'), ('LENOVO', 'LENOVO'), ('PROD_BRIK', 'PROD_BRIK'), ('STATIC', 'STATIC'), ('STATIC_ROBO', 'STATIC_ROBO')], help_text="Platform, one of ['AWSPOD', 'AZUREPOD', 'CISCO', 'DELL', 'DYNAPOD', 'DYNAPOD_ROBO', 'HPE', 'LENOVO', 'PROD_BRIK', 'STATIC', 'STATIC_ROBO']", max_length=12),
        ),
    ]
