# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0015_add_hyperv_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='fc_aix_agent',
            field=models.BooleanField(default=False, help_text='Has AIX host which has access to Pure FC LUN'),
        ),
        migrations.AddField(
            model_name='rktestyml',
            name='fc_linux_agent',
            field=models.BooleanField(default=False, help_text='Has Linux host which has access to Pure FC LUN'),
        ),
    ]
