# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-07 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0017_vcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='vcloud_8_2',
            field=models.BooleanField(default=False, help_text='Has VvCloud Director 8.2'),
        ),
    ]
