# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_legacy_items', '0018_vcd_8_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='stronger',
            field=models.BooleanField(default=False, help_text='Has double the compute power (4 vCPUs for DYNAPOD)'),
        ),
        migrations.AlterField(
            model_name='rktestyml',
            name='vcloud_8_1',
            field=models.BooleanField(default=False, help_text='Has vCloud Director 8.1'),
        ),
        migrations.AlterField(
            model_name='rktestyml',
            name='vcloud_8_2',
            field=models.BooleanField(default=False, help_text='Has vCloud Director 8.2'),
        ),
        migrations.AlterField(
            model_name='rktestyml',
            name='vcloud_9_0',
            field=models.BooleanField(default=False, help_text='Has vCloud Director 9.0'),
        ),
    ]
