# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def change_existing_networks(apps, schema_editor):
    RktestYml = apps.get_model('bodega_legacy_items', 'RktestYml')
    Network = apps.get_model('bodega_core', 'Network')

    for rktest_yml in RktestYml.objects.all():
        location = rktest_yml.location
        network = Network.objects.get(location=location,
                                      name='native')
        rktest_yml.network = network
        rktest_yml.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0013_network'),
        ('bodega_legacy_items', '0019_rktestyml_stronger'),
    ]

    operations = [
        migrations.AddField(
            model_name='rktestyml',
            name='network',
            field=models.ForeignKey(default=1,
                                    help_text='The network of this RktestYml.',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='bodega_core.Network'),
            preserve_default=False,
        ),
        migrations.RunPython(change_existing_networks,
                             reverse_code=migrations.RunPython.noop
        ),
    ]
