# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-22 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0011_stockroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrikStockroom',
            fields=[
                ('stockroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Stockroom')),
                ('name', models.CharField(max_length=255)),
                ('pxe_server_ip', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.stockroom',),
        ),
        migrations.CreateModel(
            name='PhysicalCdmNode',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('serial_number', models.CharField(max_length=255)),
                ('stockroom', models.ForeignKey(help_text='Stockroom for this brik', on_delete=django.db.models.deletion.CASCADE, to='bodega_physical.BrikStockroom')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
