# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-28 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0007_add_new_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbuntuMachine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('version', models.CharField(choices=[(b'14.04', b'14.04')], default=b'14.04', help_text=b"Version, one of ['14.04']", max_length=16)),
                ('model', models.CharField(choices=[(b'aws-m4.large', b'aws-m4.large')], default=b'aws-m4.large', help_text=b"Model, one of ['aws-m4.large']", max_length=16)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text=b'The location of this UbuntuMachine.', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
