# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0008_tab'),
        ('bodega_generic_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MssqlServer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('version', models.CharField(choices=[(b'windows2012', b'windows2012')], default=b'windows2012', help_text=b"Version, one of ['windows2012']", max_length=16)),
                ('model', models.CharField(choices=[(b'aws-m4.large', b'aws-m4.large')], default=b'aws-m4.large', help_text=b"Model, one of ['aws-m4.large']", max_length=16)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text=b'The location of this MssqlServer.', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
