# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0008_tab'),
        ('bodega_generic_items', '0002_mssqlserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('ip', models.CharField(help_text=b'The IPv4 address', max_length=15, unique=True)),
                ('location', models.ForeignKey(help_text=b'The location of this IpAddress.', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
