# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_generic_items', '0005_update_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubuntumachine',
            name='disk_size',
            field=models.IntegerField(choices=[(32, 32), (64, 64), (128, 128), (256, 256)], default=32, help_text='Disk size in GB, one of [32, 64, 128, 256]'),
        ),
        migrations.AlterField(
            model_name='ubuntumachine',
            name='model',
            field=models.CharField(default='aws-t2.large', max_length=64),
        ),
    ]
