# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-19 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_generic_items', '0006_change_model_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mssqlserver',
            name='model',
            field=models.CharField(default='aws-t2.large', max_length=16),
        ),
    ]
