# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-04 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_generic_items', '0008_ubuntumachine_root_disk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubuntumachine',
            name='kernel_version',
            field=models.CharField(choices=[('3.13', '3.13'), ('4.13', '4.13')], default='4.13', help_text="Kernel version, one of ['3.13', '4.13']", max_length=16),
        ),
    ]
