# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_generic_items', '0009_ubuntumachine_kernel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubuntumachine',
            name='root_disk_size',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (25, 25), (100, 100)], default=5, help_text='Root disk size in GB, one of [5, 10, 25, 100]'),
        ),
    ]
