# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0004_farm_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('boolean', models.BooleanField(default=False)),
                ('string', models.CharField(blank=True, max_length=255)),
                ('choice', models.CharField(choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D')], max_length=4)),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
