# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_test_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('number', models.IntegerField(blank=False, null=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
