# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0007_add_new_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdmNode',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('model', models.CharField(choices=[(b'AWS-M4.XLARGE', b'AWS-M4.XLARGE')], help_text=b"Model, one of ['AWS-M4.XLARGE']", max_length=16)),
                ('artifacts_url', models.CharField(blank=True, default=b'', help_text=b'Tivan style artifacts metadata containing information about the build to install on this CdmNode.', max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text=b'The location of this CdmNode.', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
