# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_core', '0008_tab'),
        ('bodega_cdm_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdmCluster',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('artifacts_url', models.CharField(blank=True, default=b'', help_text=b'Tivan style artifacts metadata containing information about the build to install and bootstrap on this CdmCluster.', max_length=255)),
                ('node_count', models.IntegerField(default=4, help_text=b'Number of nodes in this CdmCluster')),
                ('model', models.CharField(choices=[(b'aws-m4.xlarge', b'aws-m4.xlarge')], help_text=b"Model, one of ['aws-m4.xlarge']", max_length=16)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(help_text=b'The location of this CdmCluster.', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
        migrations.AlterField(
            model_name='cdmnode',
            name='model',
            field=models.CharField(choices=[(b'aws-m4.xlarge', b'aws-m4.xlarge')], help_text=b"Model, one of ['aws-m4.xlarge']", max_length=16),
        ),
    ]
