# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_cdm_items', '0002_cdm_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdmcluster',
            name='node_count',
            field=models.IntegerField(default=3, help_text=b'Number of nodes in this CdmCluster'),
        ),
    ]
