# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0012_order_tab_based_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsxHost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('version', models.CharField(choices=[('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VCenter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('version', models.CharField(choices=[('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5')], max_length=3)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VSphereFarm',
            fields=[
                ('farm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Farm')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.farm',),
        ),
        migrations.CreateModel(
            name='VSphereVirtualMachine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('_name', models.CharField(max_length=255)),
                ('instance_uuid', models.CharField(max_length=64)),
                ('moid', models.CharField(max_length=255)),
                ('vcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='bodega_vsphere.VCenter')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
        migrations.AddField(
            model_name='vcenter',
            name='vsphere_farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcenters', to='bodega_vsphere.VSphereFarm'),
        ),
        migrations.AddField(
            model_name='esxhost',
            name='vcenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esx_hosts', to='bodega_vsphere.VCenter'),
        ),
    ]
