# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_vsphere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esxhost',
            name='hardware',
            field=models.CharField(choices=[('spotty1', 'Microcloud with possible oversubscribing'), ('memory1', '2u4n / Fat Twin hardware')], default='spotty1', max_length=10),
            preserve_default=False,
        ),
    ]
