# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0007_add_new_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesFarm',
            fields=[
                ('farm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Farm')),
                ('url', models.CharField(max_length=255)),
                ('ca_cert', models.TextField()),
                ('namespace', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('location', models.ForeignKey(help_text=b'The location of this KubernetesFarm', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            bases=('bodega_core.farm',),
        ),
        migrations.CreateModel(
            name='KubernetesPod',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('_name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega_kubernetes.KubernetesFarm')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
        migrations.AlterUniqueTogether(
            name='kubernetesfarm',
            unique_together=set([('url', 'namespace')]),
        ),
    ]
