# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_kubernetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetesfarm',
            name='location',
            field=models.ForeignKey(help_text='The location of this KubernetesFarm', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location'),
        ),
    ]
