# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celery_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task', models.CharField(max_length=255)),
                ('root_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meth', models.CharField(blank=True, max_length=255, null=True)),
                ('shadow', models.CharField(blank=True, max_length=255, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('retries', models.IntegerField(blank=True, null=True)),
                ('soft_time_limit', models.DurationField(blank=True, null=True)),
                ('hard_time_limit', models.DurationField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('args_json', models.TextField()),
                ('kwargs_json', models.TextField()),
                ('embed_json', models.TextField()),
                ('time_published', models.DateTimeField(auto_now_add=True)),
                ('task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery_results.TaskResult')),
            ],
        ),
    ]
