# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_core', '0007_add_new_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdDevMachine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bodega_core.Item')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, default=b'', help_text=b'Contents of .sd_dev_bootstrap_hash to determine bootstrap version.', max_length=64)),
                ('location', models.ForeignKey(help_text=b'The location of this SdDevMachine', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('bodega_core.item',),
        ),
    ]
