# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_sd_dev_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sddevmachine',
            name='privileged_mode',
            field=models.BooleanField(default=False, help_text=b'Has full root/kernel capabilities.'),
        ),
    ]
