# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_sd_dev_items', '0002_sddevmachine_privileged_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sddevmachine',
            name='model',
            field=models.CharField(choices=[(b'kubernetes', b'kubernetes')], blank=False, null=False, default='kubernetes', help_text=b"Model, one of ['kubernetes']", max_length=16),
            preserve_default=False,
        ),
    ]
