# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_sd_dev_items', '0003_sddevmachine_model_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sddevmachine',
            name='model',
            field=models.CharField(choices=[(b'aws-m4.2xlarge', b'aws-m4.2xlarge'), (b'aws-m4.large', b'aws-m4.large'), (b'kubernetes', b'kubernetes')], help_text=b"Model, one of ['aws-m4.2xlarge', 'aws-m4.large', 'kubernetes']", max_length=16),
        ),
    ]
