# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_sd_dev_items', '0004_model_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sddevmachine',
            name='location',
            field=models.ForeignKey(help_text='The location of this SdDevMachine', on_delete=django.db.models.deletion.CASCADE, to='bodega_core.Location'),
        ),
        migrations.AlterField(
            model_name='sddevmachine',
            name='model',
            field=models.CharField(choices=[('aws-m4.2xlarge', 'aws-m4.2xlarge'), ('aws-m4.large', 'aws-m4.large'), ('kubernetes', 'kubernetes')], help_text="Model, one of ['aws-m4.2xlarge', 'aws-m4.large', 'kubernetes']", max_length=16),
        ),
        migrations.AlterField(
            model_name='sddevmachine',
            name='privileged_mode',
            field=models.BooleanField(default=False, help_text='Has full root/kernel capabilities.'),
        ),
        migrations.AlterField(
            model_name='sddevmachine',
            name='version',
            field=models.CharField(blank=True, default='', help_text='Contents of .sd_dev_bootstrap_hash to determine bootstrap version.', max_length=64),
        ),
    ]
