# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-19 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega_sd_dev_items', '0005_update_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sddevmachine',
            name='model',
            field=models.CharField(max_length=16),
        ),
    ]
